export const mockData = [
  {
    title: "Claim",
    created: "12/04/2021",
    type: "Hardware",
    status: "Declined",
    actions: "Browse",
  },
  {
    title: "Claim",
    created: "13/04/2021",
    type: "Software",
    status: "New",
    actions: "Browse",
  },
  {
    title: "Claim",
    created: "14/04/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    title: "Claim",
    created: "19/04/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    title: "Claim",
    created: "27/04/2021",
    type: "Networking",
    status: "Done",
    actions: "Browse",
  },
  {
    title: "Claim",
    created: "02/05/2021",
    type: "Hardware",
    status: "New",
    actions: "Browse",
  },
  {
    title: "Claim",
    created: "10/05/2021",
    type: "Networking",
    status: "Declined",
    actions: "Browse",
  },
  {
    title: "Claim",
    created: "12/05/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    title: "Claim",
    created: "19/05/2021",
    type: "Troubleshooting",
    status: "Declined",
    actions: "Browse",
  },
  {
    title: "Claim",
    created: "26/05/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
];
