export const mockData = [
  {
    id: 1,
    title: "Claim",
    created: "12/04/2021",
    type: "Hardware",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 2,
    title: "Claim",
    created: "13/04/2021",
    type: "Software",
    status: "New",
    actions: "Browse",
  },
  {
    id: 3,
    title: "Claim",
    created: "14/04/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 4,
    title: "Claim",
    created: "19/04/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 5,
    title: "Claim",
    created: "27/04/2021",
    type: "Networking",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 6,
    title: "Claim",
    created: "02/05/2021",
    type: "Hardware",
    status: "New",
    actions: "Browse",
  },
  {
    id: 7,
    title: "Claim",
    created: "10/05/2021",
    type: "Networking",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 8,
    title: "Claim",
    created: "12/05/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 9,
    title: "Claim",
    created: "19/05/2021",
    type: "Troubleshooting",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 10,
    title: "Claim",
    created: "26/05/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 1,
    title: "Claim",
    created: "12/04/2021",
    type: "Hardware",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 2,
    title: "Claim",
    created: "13/04/2021",
    type: "Software",
    status: "New",
    actions: "Browse",
  },
  {
    id: 3,
    title: "Claim",
    created: "14/04/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 4,
    title: "Claim",
    created: "19/04/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 5,
    title: "Claim",
    created: "27/04/2021",
    type: "Networking",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 6,
    title: "Claim",
    created: "02/05/2021",
    type: "Hardware",
    status: "New",
    actions: "Browse",
  },
  {
    id: 7,
    title: "Claim",
    created: "10/05/2021",
    type: "Networking",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 8,
    title: "Claim",
    created: "12/05/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 9,
    title: "Claim",
    created: "19/05/2021",
    type: "Troubleshooting",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 10,
    title: "Claim",
    created: "26/05/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 1,
    title: "Claim",
    created: "12/04/2021",
    type: "Hardware",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 2,
    title: "Claim",
    created: "13/04/2021",
    type: "Software",
    status: "New",
    actions: "Browse",
  },
  {
    id: 3,
    title: "Claim",
    created: "14/04/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 4,
    title: "Claimffffff",
    created: "19/04/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 5,
    title: "Claim",
    created: "27/04/2021",
    type: "Networking",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 6,
    title: "Claim",
    created: "02/05/2021",
    type: "Hardware",
    status: "New",
    actions: "Browse",
  },
  {
    id: 7,
    title: "Claim",
    created: "10/05/2021",
    type: "Networking",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 8,
    title: "Claim",
    created: "12/05/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 9,
    title: "Claim",
    created: "19/05/2021",
    type: "Troubleshooting",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 10,
    title: "ffffff",
    created: "26/05/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 1,
    title: "Claim",
    created: "12/04/2021",
    type: "Hardware",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 2,
    title: "Claim",
    created: "13/04/2021",
    type: "Software",
    status: "New",
    actions: "Browse",
  },
  {
    id: 3,
    title: "Claim",
    created: "14/04/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 4,
    title: "Claim",
    created: "19/04/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 5,
    title: "Claim",
    created: "27/04/2021",
    type: "Networking",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 6,
    title: "Claim",
    created: "02/05/2021",
    type: "Hardware",
    status: "New",
    actions: "Browse",
  },
  {
    id: 7,
    title: "Claim",
    created: "10/05/2021",
    type: "Networking",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 8,
    title: "Claim",
    created: "12/05/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 9,
    title: "Claim",
    created: "19/05/2021",
    type: "Troubleshooting",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 10,
    title: "Claim",
    created: "26/05/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 1,
    title: "Claim",
    created: "12/04/2021",
    type: "Hardware",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 2,
    title: "Claim",
    created: "13/04/2021",
    type: "Software",
    status: "New",
    actions: "Browse",
  },
  {
    id: 3,
    title: "Claim",
    created: "14/04/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 4,
    title: "Claim",
    created: "19/04/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 5,
    title: "Claim",
    created: "27/04/2021",
    type: "Networking",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 6,
    title: "Claim",
    created: "02/05/2021",
    type: "Hardware",
    status: "New",
    actions: "Browse",
  },
  {
    id: 7,
    title: "Claim",
    created: "10/05/2021",
    type: "Networking",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 8,
    title: "Claim",
    created: "12/05/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 9,
    title: "Claim",
    created: "19/05/2021",
    type: "Troubleshooting",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 10,
    title: "Claim",
    created: "26/05/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 1,
    title: "Claim",
    created: "12/04/2021",
    type: "Hardware",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 2,
    title: "Claim",
    created: "13/04/2021",
    type: "Software",
    status: "New",
    actions: "Browse",
  },
  {
    id: 3,
    title: "Claim",
    created: "14/04/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 4,
    title: "Claimffffff",
    created: "19/04/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 5,
    title: "Claim",
    created: "27/04/2021",
    type: "Networking",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 6,
    title: "Claim",
    created: "02/05/2021",
    type: "Hardware",
    status: "New",
    actions: "Browse",
  },
  {
    id: 7,
    title: "Claim",
    created: "10/05/2021",
    type: "Networking",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 8,
    title: "Claim",
    created: "12/05/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 9,
    title: "Claim",
    created: "19/05/2021",
    type: "Troubleshooting",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 10,
    title: "ffffff",
    created: "26/05/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 1,
    title: "Claim",
    created: "12/04/2021",
    type: "Hardware",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 2,
    title: "Claim",
    created: "13/04/2021",
    type: "Software",
    status: "New",
    actions: "Browse",
  },
  {
    id: 3,
    title: "Claim",
    created: "14/04/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 4,
    title: "Claim",
    created: "19/04/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 5,
    title: "Claim",
    created: "27/04/2021",
    type: "Networking",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 6,
    title: "Claim",
    created: "02/05/2021",
    type: "Hardware",
    status: "New",
    actions: "Browse",
  },
  {
    id: 7,
    title: "Claim",
    created: "10/05/2021",
    type: "Networking",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 8,
    title: "Claim",
    created: "12/05/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 9,
    title: "Claim",
    created: "19/05/2021",
    type: "Troubleshooting",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 10,
    title: "Claim",
    created: "26/05/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 1,
    title: "Claim",
    created: "12/04/2021",
    type: "Hardware",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 2,
    title: "Claim",
    created: "13/04/2021",
    type: "Software",
    status: "New",
    actions: "Browse",
  },
  {
    id: 3,
    title: "Claim",
    created: "14/04/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 4,
    title: "Claim",
    created: "19/04/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 5,
    title: "Claim",
    created: "27/04/2021",
    type: "Networking",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 6,
    title: "Claim",
    created: "02/05/2021",
    type: "Hardware",
    status: "New",
    actions: "Browse",
  },
  {
    id: 7,
    title: "Claim",
    created: "10/05/2021",
    type: "Networking",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 8,
    title: "Claim",
    created: "12/05/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 9,
    title: "Claim",
    created: "19/05/2021",
    type: "Troubleshooting",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 10,
    title: "Claim",
    created: "26/05/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 1,
    title: "Claim",
    created: "12/04/2021",
    type: "Hardware",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 2,
    title: "Claim",
    created: "13/04/2021",
    type: "Software",
    status: "New",
    actions: "Browse",
  },
  {
    id: 3,
    title: "Claim",
    created: "14/04/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 4,
    title: "Claimffffff",
    created: "19/04/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 5,
    title: "Claim",
    created: "27/04/2021",
    type: "Networking",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 6,
    title: "Claim",
    created: "02/05/2021",
    type: "Hardware",
    status: "New",
    actions: "Browse",
  },
  {
    id: 7,
    title: "Claim",
    created: "10/05/2021",
    type: "Networking",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 8,
    title: "Claim",
    created: "12/05/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 9,
    title: "Claim",
    created: "19/05/2021",
    type: "Troubleshooting",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 10,
    title: "ffffff",
    created: "26/05/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 1,
    title: "Claim",
    created: "12/04/2021",
    type: "Hardware",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 2,
    title: "Claim",
    created: "13/04/2021",
    type: "Software",
    status: "New",
    actions: "Browse",
  },
  {
    id: 3,
    title: "Claim",
    created: "14/04/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 4,
    title: "Claim",
    created: "19/04/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 5,
    title: "Claim",
    created: "27/04/2021",
    type: "Networking",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 6,
    title: "Claim",
    created: "02/05/2021",
    type: "Hardware",
    status: "New",
    actions: "Browse",
  },
  {
    id: 7,
    title: "Claim",
    created: "10/05/2021",
    type: "Networking",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 8,
    title: "Claim",
    created: "12/05/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 9,
    title: "Claim",
    created: "19/05/2021",
    type: "Troubleshooting",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 10,
    title: "Claim",
    created: "26/05/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 1,
    title: "Claim",
    created: "12/04/2021",
    type: "Hardware",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 2,
    title: "Claim",
    created: "13/04/2021",
    type: "Software",
    status: "New",
    actions: "Browse",
  },
  {
    id: 3,
    title: "Claim",
    created: "14/04/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 4,
    title: "Claim",
    created: "19/04/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 5,
    title: "Claim",
    created: "27/04/2021",
    type: "Networking",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 6,
    title: "Claim",
    created: "02/05/2021",
    type: "Hardware",
    status: "New",
    actions: "Browse",
  },
  {
    id: 7,
    title: "Claim",
    created: "10/05/2021",
    type: "Networking",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 8,
    title: "Claim",
    created: "12/05/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 9,
    title: "Claim",
    created: "19/05/2021",
    type: "Troubleshooting",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 10,
    title: "Claim",
    created: "26/05/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 1,
    title: "Claim",
    created: "12/04/2021",
    type: "Hardware",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 2,
    title: "Claim",
    created: "13/04/2021",
    type: "Software",
    status: "New",
    actions: "Browse",
  },
  {
    id: 3,
    title: "Claim",
    created: "14/04/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 4,
    title: "Claimffffff",
    created: "19/04/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 5,
    title: "Claim",
    created: "27/04/2021",
    type: "Networking",
    status: "Done",
    actions: "Browse",
  },
  {
    id: 6,
    title: "Claim",
    created: "02/05/2021",
    type: "Hardware",
    status: "New",
    actions: "Browse",
  },
  {
    id: 7,
    title: "Claim",
    created: "10/05/2021",
    type: "Networking",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 8,
    title: "Claim",
    created: "12/05/2021",
    type: "Troubleshooting",
    status: "In Progress",
    actions: "Browse",
  },
  {
    id: 9,
    title: "Claim",
    created: "19/05/2021",
    type: "Troubleshooting",
    status: "Declined",
    actions: "Browse",
  },
  {
    id: 10,
    title: "ffffff",
    created: "26/05/2021",
    type: "Software",
    status: "Done",
    actions: "Browse",
  },
];
